# Custom config for AWS BeanStalk platform

branch-defaults:
  master:
    environment: vigneshdemo-env
  global: 
  application_name: vigneshdemo
  AWS_ACCESS_KEY_ID: AKIA6Q42TZMMGZB6LP4C
  AWS_SECRET_KEY_ID: Xid38xVjT+YCTrQ3f3T9j3y68qE5LTBJk0F0sMWU
  default_platform: Java 8 running on 64bit Amazon Linux/2.11.1
  default_region: us-east-1
  sc: git
deploy:
  artifact: target/demo-1.0.jar
