# Custom config for AWS BeanStalk platform

branch-defaults:
  master:
    environment: Sample-env
    group_suffix: null
global:
  application_name: sample
  branch: null
  default_ec2_keyname: sample
  default_platform: java 8
  default_region: us-east-1
  include_git_submodules: true
  instance_profile: null
  platform_name: null
  platform_version: null
  profile: null
  repository: null
  sc: git
deploy:
  artifact: target/demo-1.0.jar
